### ISSUE TITLE
Write parser and converter for every library separately

### ISSUE THREAD

**Issue by willbasky** [kowainik/tomland#111]
Sub Issue for #98 

There are several libs to parse Toml:
- [x] #122 htoml
- [x] #123 htoml-megaparsec
- #124 toml-parser (is too old to use without conflict)
- #125 toml (is too old to use without conflict)

Some of them have `parse`like, others have `decode` like functions. To benchmark them with `tomland` the equality is required. 

So we need 3 function for all libraries only for benchmarking. Signatures:
1. `parse :: Text -> TOML`
2. `toHaskell :: TOML -> HaskellType`
3. `decode :: Text -> HaskellType`

**Comment by ChShersh** [comment]
@willbasky I think that this is done for `tomland`. Also, I guess that this issue should be separated into 4 issues: 1 per every library.

No need to rename or change anything in this particular issue, it can be a parent issue for subtasks.

Unfortunately, we can't write generic functions like `runTomlCodec :: TomlCodec a -> TOML -> Either DecodeException a` for every library. These functions will be specific to types for each library. So in `htoml` this could be `Value` instead of `TomlCodec`.

**Comment by willbasky** [comment]
Should we remove `runTomlCodec` from implementing for other libraries?

**Comment by ChShersh** [comment]
@willbasky `runTomlCodec` makes sense only for `tomland`. Other libraries won't work with `TomlCodec` object, they will use their own types.

**Comment by ChShersh** [comment]
@willbasky Yeah, we won't measure pretty-printing performance, only parsing. Especially when `tomland` library is the only library that supports pretty-printing of TOML
