### ISSUE TITLE
Add parsing of inline tables

### ISSUE THREAD

**Issue by ChShersh** [kowainik/tomland#14]
This might be convenient with #13.

**Comment by vrom911** [comment]
Blocked by #13

**Comment by jiegillet** [comment]
I played around a bit and I wrote a parser for inline tables, but it only works for simple key/value pairs at the moment.
When I tried to parse
```
table = { x = 1, y = 2, subtable = { deep = true } }
```
I realized that it's much harder because key/value pairs and tables are stored in different data structures. Related problem:
```
x = 1
table = { hello = "world"}
y = 2
```
which should be the same as
```
x = 1
y = 2
table = { hello = "world"}
```
won't be parsed easily since it once again mixes key/value and table data types.  One possibility to change that is to make the parsers return `TOML` values and fuse them later.

I also ran into something that bothers me a bit. The toml files
```
[dog]
type.name = "pug"
``` 
and 
```
dog.type.name = "pug"
``` 
or 
```
[dog.type]
name = "pug"
``` 
should, to my understanding, be parsed to the same tree, but since keys associated to values are separate from the table keys, all three input are saved differently. I think they should all be saved as the last input would be. That would probably help in checking name collisions and such.

What do you think?

**Comment by ChShersh** [comment]
@jiegillet 

> should, to my understanding, be parsed to the same tree

I don't think this should be parsed to the same tree. Maybe only if you parse and then convert to JSON these configurations can have the same structure. But with TOML you can visually separate keys on tables and key-value pairs. There're two reasons to store keys and tables separately — optimisations and simplicity.

You can see more uniform way to represent TOML in this library:

* https://hackage.haskell.org/package/toml-parser-0.1.0.0/docs/TOML.html#v:parseTOML

But the goal of `tomland` is not to be able to parse structurally equivalent configurations, it's more about more clear specification of configuration format and adding restrictions. Also, it brings a lot of complexity to the code if you want to be able to specify path for key like `dog.type.name` and be able to parse different TOML configurations. Probably somebody can do this in different library 🙂 

Regarding parsing things like this one:

```haskell
x = 1
table = { hello = "world"}
y = 2
```

I think that solution can be to replace the type of `keyValP` from the current one:

https://github.com/kowainik/tomland/blob/713f23258ca2f1d1a31bc6d360269aad06ce0608/src/Toml/Parser/TOML.hs#L17

To something like:

```haskell
keyValP :: Parser (Key, Either TOML AnyValue)
```

And then you can convert `[(Key, TOML)]` and `[(Key, Either TOML AnyValue)]` to `TOML`.

**Comment by jiegillet** [comment]
>  There're two reasons to store keys and tables separately — optimisations and simplicity.

Well then most of my problems go away, that's fine :)

> I think that solution can be to replace the type of `keyValP` from the current one
> To something like:
> 
> ```haskell
> keyValP :: Parser (Key, Either TOML AnyValue)
> ```
> 
> And then you can convert `[(Key, TOML)]` and `[(Key, Either TOML AnyValue)]` to `TOML`.

I had explored that idea for a bit before I questioned the key/value - table structure, I'm glad that it wasn't a stupid idea ^^
