### ISSUE TITLE
Change the type of `wrapper` function to get rid of `Key` argument

### ISSUE THREAD

**Issue by ChShersh** [kowainik/tomland#140]
Currently:

```haskell
wrapper :: forall b a. Coercible a b => (Key -> TomlCodec a) -> Key -> TomlCodec b
```

Want:

```haskell
diwrap :: forall b a. Coercible a b => BiCodec r w a -> BiCodec r w b
```

**Comment by jiegillet** [comment]
I was about to write this in #140, but maybe it's better to discuss here.

How about `mdimap`? Maybe it should also move to `Toml.Bi.Monad`? 
Actually, does it even make sense to keep if since it's basically the same as `prism`?
`dioptional` is sort of like `_Just`.
`diwrap` could also be `_Coerce :: Coercible a b => _BiMap a AnyValue -> _BiMap b AnyValue`.

Maybe it's best if people only have one way to  match their data...

**Comment by jiegillet** [comment]
I'm sorry if I'm going a bit too far, you don't have to consider it seriously, but here's an alternative idea for the API. 

Right now people have to juggle with combinators and `BiMap`s, I feel it would be better if there was only one way to do things. And since all the combinators are of the form `foo = match _Foo` maybe `BiMap` should be the one way.

Right now those 2 ways are equivalent:
```haskell
example1, example2 :: TomlCodec Example
example1 = Example
    <$> bool "foo" .= foo
    <*> dioptional (int "bar") .= bar
example2 = Example 
    <$> match _Bool "foo" .= foo 
    <*> match (_Just >>> _Int) "bar" .= bar
```
but if we got rid of all the combinators like `bool`and `int` introduced
```haskell
infixl 5 .$
(.$) :: (Typeable field) => BiMap field AnyValue -> Key -> (object -> field) -> Codec Env St object field
(.$) bimap key getter = codec { codecWrite = codecWrite codec . getter }
  where
    codec = match bimap key

infixl 5 .==
(.==) :: (a -> b) -> a -> b
(.==) = ($)

_Maybe :: BiMap a AnyValue -> BiMap (Maybe a) AnyValue
_Maybe =_Maybe = (>>>) _Just
```

then the only way to have `example` would be

```haskell
example = Example 
    <$> _Bool .$ "foo" .== foo 
    <*> _Maybe _Int .$ "bar" .== bar
```
I'm not super happy about having an extra operator, but it's a price to pay.
`diwrap` get replaced by  `_ Coerce `
```haskell
example = Example 
    <$> _Bool .$ "foo" .== foo 
    <*> _Coerce _Int .$ "bar" .== bar -- bar :: Example -> N  -- new type N = N Int 
```
`dimap` gets replaced by `iso` and `mdimap` by `prism`.

We can also introduce `_Either a b :: BiMap a AnyValue -> BiMap b AnyValue -> BiMap (Either a b) AnyValue` and more things in the `BiMap` module.

**Comment by ChShersh** [comment]
@jiegillet Regarding `mdimap`: yeah, I think you can remove this combinator. After API change is not needed anymore for what is was supposed to be used. Instead of using `mdimap showGhcVer parseGhcVer` you can use `match (prism showGhcVer parseGhcVer)` to have more consistent API. You can create issue regarding removal of `mdimap` :+1: 

> Right now those 2 ways are equivalent:

This is actually not true. `dioptional` also returns `Nothing` when such key is not present. Consider the following TOML:
```toml
foo = true
```
Decoding this toml with `example1` returns `Example {foo = True, bar = Nothing}` while decoding it with `example2` returns:

```
play-tomland: Couldnt parse file foo.toml: "Key bar not found"
```

I agree with the following convention: if we have `BiMap` with name `_Foo` there's should be `TomlCodec` with name `foo` which should be implemented as `match _Foo`. But it still makes sense to have both `BiMap` and `TomlCodec` because some things can be done only on `Codec` level. `BiMap` is only about values -- very primitive types, while `TomlCodec` is about more complex types. For example, for now we have the following combinator:

```haskell
arrayOf :: BiMap a AnyValue -> Key -> TomlCodec [a]
```

This combinator takes bidirectional converter for value and returns codec for list of values. It works with primitive types. After we implement array of tables, we will have the following combinator:

```haskell
list :: TomlCodec a -> Key -> TomlCodec [a]
```

It takes codec for complex type (like `User`) and works with `tableArrays` field of `TOML` data type. This combinator should be used for parsing list of more complex types. So the types are similar but the semantics are slightly different.

**Comment by jiegillet** [comment]
You're right, the two examples are not identical. I guess I should be more careful when coding at 2AM :)
